# Generated by Django 4.0.5 on 2022-06-08 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolioapp', '0003_portfolio_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('averagePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolioSlug', models.CharField(blank=True, max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=4)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('portfolio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='portfolioapp.portfolio')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
