# Generated by Django 4.0.5 on 2022-06-08 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
