# Generated by Django 4.0.5 on 2022-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0002_ticker_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
