# Generated by Django 4.0.5 on 2022-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0004_alter_ticker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
