# Generated by Django 4.0.5 on 2022-06-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0006_alter_ticker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
