# Generated by Django 4.0.5 on 2022-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0008_alter_ticker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
