version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/stock_portfolio/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
    ports:
      - 80:80
  django_container_gunicorn:
    image: stock_portfolio_backend_image:8
    networks:
      - network
    volumes:
      - static-volume:/home/stock_portfolio/stock_portfolio_backend/staticfiles
    secrets:
      - MARIADB_PASSWORD
      - DJANGO_SECRET_KEY
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD  
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  network:

volumes:
  static-volume:
  maria-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true