# Generated by Django 4.0.5 on 2022-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='portfolioSlug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
