# Generated by Django 4.0.5 on 2022-06-16 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_portfolio_username'),
        ('activityapp', '0002_activity_portfolioslug_activity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='portfolio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='portfolioapp.portfolio'),
        ),
    ]
