# Generated by Django 4.0.5 on 2022-06-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0003_alter_activity_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
