# Generated by Django 4.0.5 on 2022-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0005_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
