# Generated by Django 4.0.5 on 2022-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0006_activity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
