# Generated by Django 4.0.5 on 2022-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0007_activity_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
