# Generated by Django 4.0.5 on 2022-06-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='alpaca_api_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='alpaca_secret_key',
        ),
    ]
