# Generated by Django 4.0.5 on 2022-06-04 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_remove_account_alpaca_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alpaca_api_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='alpaca_secret_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
