# Generated by Django 4.0.5 on 2022-06-04 09:22

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_account_alpaca_api_key_account_alpaca_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alpaca_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=60, unique=True)),
        ),
        migrations.AlterField(
            model_name='account',
            name='alpaca_secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=60, unique=True)),
        ),
    ]
