# Generated by Django 4.0.5 on 2022-06-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_alter_account_alpaca_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='paper_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='alpaca_api_key',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='alpaca_secret_key',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
